
# my info
author:
  name: Cologler

# To enable pagination for your blog, add a line to the _config.yml file that specifies how many items should be displayed per page:
paginate: 5
paginate_path: "page:num"

# set link.
permalink: /:title.html

# Conversion
kramdown:
  input: GFM

gems: [jekyll-paginate]

excerpt_separator: "<!-- more -->"